name: Locater

web: "[http://url_to_plugin](label)"

description:

authors:
  - Noritaka Horio

license: "MIT License"

copyright: "&copy; ${TM_FULLNAME}"

sources:
  - "Source/Core/Core.js"
  - "Source/Core/Rules.js"
  - "Source/Core/Container.js"
  - "Source/Core/Dispacher.js"
  - "Source/Core/Application.js"
  - "Source/Adapter/Adapter.js"
  - "Source/Handler/Handler.js"
  - "Source/Handler/Context.js"
  - "Source/Handler/DebugHandler.js"
  - "Source/Handler/CurrentPositionHandler.js"

author: Noritaka Horio

category: Interface

tags: [framework, geo]

current: 1.0

docs: http://url_to_plugin_docs

demo: http://url_to_plugin_demo