name: Locater

web: "[http://sharedhat.com](http://sharedhat.com)"

description: "Locater is an application framework using Geolocation API Specification."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://holyshared.github.com/Locater/license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - "Source/Core/Core.js"
  - "Source/Core/Rules.js"
  - "Source/Core/Dispacher.js"
  - "Source/Core/Application.js"
  - "Source/Adapter/Adapter.js"
  - "Source/Handler/Handler.js"
  - "Source/Handler/Context.js"
  - "Source/Handler/DebugHandler.js"
  - "Source/Handler/CurrentPositionHandler.js"

author: Noritaka Horio

category: Realtime

tags: [framework, geo, html5, application]

current: 1.0

docs: http://holyshared.github.com/Locater/docs

demo: http://holyshared.github.com/Locater/